<a href="https://colab.research.google.com/github/alimoorreza/CS167-fall26-notes/blob/main/Day07_Introduction_to_Scikit_Learn_and_kNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day07
## Introduction to Scikit Learn and implementation of KNN using scikit learn

#### CS167: Machine Learning, Fall 2026


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_fall26/cs167_syllabus_fall26.pdf)

## Quick Review:

**k Nearest Neighbors**: predict the most commonly occuring class of the *k nearest neighbors*.

Three main steps:
1. Calculate the distance between the new point (e.g. the Iris we would like to make a prediction on), and the existing training examples.

2. Sort the data by the newly calculated distance so that the nearest training examples are first

3. Take the top `k` neighbors and:
    - if the problem is a *classification*, **take the mode of the target variable** to find the most commonly appearing class and return that as your prediction.
    - if the problem is a *regression*, **take the average of the target variables for the k closest neighbors** and return that as your prediction

# Implement kNN in Python/Pandas:

[Please, take a look at the notebook from the last lecture.](https://github.com/alimoorreza/CS167-fall26-notes/blob/main/Day06_kNN.ipynb)

# Introduction to Scikit Learn:

`scikit-learn` is one of Python's main Machine Learning Libraries.

_"It is an open source machine learning library that supports supervised and unsupervised learning. It also provides various tools for model fitting, data preprocessing, model selection, model evaluation, and many other utilities."_

- built on `NumPy`, `SciPy`, and `matplotlib`
- plays nicely with `pandas`
- https://scikit-learn.org/stable/

# Overview of the Scikit Learn 'Algorithm':

In Scikit Learn (`sklearn`), we can do the following to implement kNN (or any supported machine learning algorithm):

1. Load your data using `pd.read_csv()`
2. Create `kNN classifier/regressor` object
3. Call `fit()` to train your model using the training data
4. Call `predict()` to get predictions of the new unknown sample

## All together, it looks something like this:

In [1]:
# kNN using scikit-learn algorithm implementation

import pandas
import sklearn
from sklearn import neighbors


#---------------- STEP 1 ----------------
# load data, separate the 'features'/'predictors' and the 'labels'

#---------------- STEP 2 ----------------
# Create kNN classifier/regressor object (change these parameters for Exercise #1)
#my_knn = neighbors.KNeighborsClassifier(n_neighbors=17)


#---------------- STEP 3 ----------------
# Call fit (to train the classification/regression model)
#my_knn.fit(train_data, train_labels)


#---------------- STEP 4 ----------------
# Call predict to generate predictions

# Now, let's go through step-by-step:

## Step 0-1: Import libraries and load your data

We should be pretty familiar with this one.
- mount your drive
- import any relevant libraires
- use `pd.read_csv()` to load in your dataset

In [2]:
# Mount your drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# import libraries
import pandas
import sklearn

#from sklearn import neighbors # importing the k-Nearest Neighbor machine learning model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

# load data
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris_data = pandas.read_csv(path)
iris_data.head()

   sepal length  sepal width  petal length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Step 1.1: Separate the `target` column and `predictor` columns from training data

In [4]:
predictors= ['sepal length', 'sepal width', 'petal length', 'petal width']
target= 'species'

train_data      = iris_data[predictors]
train_labels    = iris_data[target]
print('train_data shape:', train_data.shape, 'and train_labels shape:', train_labels.shape)

train_data shape: (150, 4) and train_labels shape: (150,)

## Step 1.2: Generate a new test sample
Let's generate a new instance with:
- 5.1 petal length, 7.2 sepal length, 1.5 petal width, and 2.5 sepal width

In [5]:
# create a new sample test value for which we don't know the 'species' (target variable) value
new_iris = {'sepal length': [7.2], 'sepal width':[2.5], 'petal length':[5.5], 'petal width':[1.5]}
test_data = pandas.DataFrame(data=new_iris)
test_data

   sepal length  sepal width  petal length  petal width
0           7.2          2.5           5.5          1.5

## Step 2: Create kNN classifier/regressor object

The syntax/wording for this is going to come directly from the `sklearn` documentation.
- [Scikit Learn kNN Classifier documentation](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier) (i.e., the classifier, not an unsupervised algorithm).
The name of the model will change based on whether you are doing a __classification__ or __regression__.
- generally in the name:
    - `neighbors.KNeighborsClassifier()`
    - `neighbors.KNeighborsRegressor()`

In [6]:
# Create kNN classifier/regressor object
from sklearn.neighbors import KNeighborsClassifier

k_value     = 5
my_knn      = KNeighborsClassifier(n_neighbors= k_value)

## Step 3: Call `fit()` to train the model

KNeighborClassifier model has a training process associated with it. Scikit learn makes it easy to train whatever model you choose by simply calling `fit()` on that model.

We generally pass two things into `fit()`:
- `train_data`: the predictor variables we want to train our model on
- `train_sln`: the labels for each training examples

In [7]:
my_knn.fit(train_data, train_labels)

KNeighborsClassifier()

## Step 4: Call `predict()` to get predictions

After our model is trained, it's time to run our testing data through our model and see what the model predicts.

Scikit learn lets us do this in one line:
- we're saving what the function is returning as `predictions`
- passing in `test_data`, which is the data without labels that was not included in training

In [8]:
predictions = my_knn.predict(test_data)
print(f'Label of the new sample according to {k_value}-NN: {predictions[0]}')

Label of the new sample according to 5-NN: Iris-virginica

#**Putting it altogether**

In [13]:
#classic scikit-learn algorithm

#---------------- STEP 0 ----------------
# import libraries
import pandas
import sklearn
from sklearn.neighbors import KNeighborsClassifier

# load data
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris_data = pandas.read_csv(path)
iris_data.head()

#---------------- STEP 1 ----------------
#1. load data
predictors   = ['sepal length', 'sepal width', 'petal length', 'petal width']
target       = 'species'
train_data   = iris_data[predictors]
train_labels = iris_data[target]
print(f"train_data.shape: {train_data.shape} and train_labels.shape: {train_labels.shape}\n\n")

new_iris     = {'sepal length': [7.2], 'sepal width':[2.5], 'petal length':[5.5], 'petal width':[1.5]}
test_data    = pandas.DataFrame(data=new_iris)
print(f"test sample: {test_data}\n\n")


#---------------- STEP 2 ----------------
#2. Create kNN classifier/regressor object
k_value = 5
my_knn = KNeighborsClassifier(n_neighbors=k_value)


#---------------- STEP 3 ----------------
#3. Call fit (to train the classification/regression model)
my_knn.fit(train_data, train_labels)


#---------------- STEP 4 ----------------
#4. Call predict to generate predictions
predictions = my_knn.predict(test_data)
print(f'Label of the new sample according to {k_value}-NN: {predictions[0]}')

train_data.shape: (150, 4) and train_labels.shape: (150,)


test sample:    sepal length  sepal width  petal length  petal width
0           7.2          2.5           5.5          1.5


Label of the new sample according to 5-NN: Iris-virginica

If you want to check the individual nearest neighbors and their labels, you can do the following. The syntax/wording for this is going to come directly from the `sklearn` documentation.
>[KNeighborsClassifier.kneighbors() method](https://scikit-learn.org/0.19/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier.kneighbors)

In [26]:
[dist, indx] = my_knn.kneighbors(test_data, k_value)
print(f"indices of the training samples are as follows: {indx}")

for i in range(len(indx[0])):

  sample_idx = indx[0][i]
  train_sample = train_data.iloc[sample_idx][ ['sepal length', 'sepal width', 'petal length', 'petal width'] ]

  print(f"train_data:({train_sample['sepal length']}",
        f"{train_sample['sepal width']}, ",
        f"{train_sample['petal length']}, ",
        f"{train_sample['petal width']}) ",
        f"and its label: {train_labels.iloc[sample_idx]}",
        f" with a distance of {dist[0][i]:.4f}" )

indices of the training samples are as follows: [[129 108 130  76 112]]
train_data:(7.2 3.0,  5.8,  1.6)  and its label: Iris-virginica  with a distance of 0.5916
train_data:(6.7 2.5,  5.8,  1.8)  and its label: Iris-virginica  with a distance of 0.6557
train_data:(7.4 2.8,  6.1,  1.9)  and its label: Iris-virginica  with a distance of 0.8062
train_data:(6.8 2.8,  4.8,  1.4)  and its label: Iris-versicolor  with a distance of 0.8660
train_data:(6.8 3.0,  5.5,  2.1)  and its label: Iris-virginica  with a distance of 0.8775

# Group exercise 1: try classification now on a new dataset vehicle.csv

Using the `vehicles.csv` dataset, let's try out sklearn with regression:
- load the data, get the right subset
- set predictors and target variables

## Step 1.1: Separate the training data

In [34]:
# load in the vehicles.csv data for scikit learn
import pandas
import numpy

# load data, get the right subset
path            = '/content/drive/MyDrive/cs167_fall26/datasets/vehicles.csv'
data            = pandas.read_csv(path, low_memory=False)
print(f"There are total {data.shape[0]} samples. We will cleanup the data first then take only a subset of rows and columns")
data.head()

There are total 42103 samples. We will cleanup the data first then take only a subset of rows and columns

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [40]:
path            = '/content/drive/MyDrive/cs167_fall26/datasets/vehicles.csv'
data            = pandas.read_csv(path, low_memory=False)
# select only a subset of rows/samples whose fuelType is 'Regular'
# among those rows, select only a subset of predictors ['year', 'cylinders', 'displ', 'comb08']
gas_vehicles    = data[data['fuelType']=='Regular'][['year', 'cylinders', 'displ', 'comb08']]
gas_vehicles.dropna(inplace=True)

# set the predictor variables and target variable
predictors      = ['year', 'cylinders', 'displ']
target          = 'comb08'

# separate the data and labels
train_data      = gas_vehicles[predictors]
train_labels    = gas_vehicles[target]
print(f"total training samples after cleanup: {train_data.shape[0]}")

total training samples after cleanup: 26860

In [36]:
train_data.head()

   year  cylinders  displ
0  1985        4.0    2.0
1  1985       12.0    4.9
2  1985        4.0    2.2
3  1985        8.0    5.2
5  1993        4.0    1.8

In [37]:
train_labels.head()

0    21
1    11
2    27
3    11
5    22
Name: comb08, dtype: int64

## Step 1.2: Generate a new test sample
Let's generate a new instance with:
- 1985 year, 5 cylinder, and 2.0 displ

In [38]:
# create a new sample test (with three predictors) but for which we don't know the 'comb08' (target variable) value
new_vehicle = {'year': [1985], 'cylinders':[4], 'displ':2.0}
test_data = pandas.DataFrame(data=new_vehicle)
test_data

   year  cylinders  displ
0  1985          4    2.0

In [44]:
# your code
from sklearn.neighbors import KNeighborsClassifier

# ...
# ...
# ...

total training samples after cleanup: 26860
kNN (classifier) predicted label: [22]

If you want to check the individual nearest neighbors and their labels, you can do the following. The syntax/wording for this is going to come directly from the `sklearn` documentation.
>[KNeighborsClassifier.kneighbors() method](https://scikit-learn.org/0.19/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier.kneighbors)

In [ ]:

[dist, indx] = my_knn.kneighbors(test_data, k_value)
print(f"indices of the training samples are as follows: {indx}")

for i in range(len(indx[0])):

  sample_idx = indx[0][i]
  train_sample = train_data.iloc[sample_idx][ ['year', 'cylinders', 'displ'] ]

  print(f"train_data:({train_sample['year']}",
        f"{train_sample['cylinders']}, ",
        f"{train_sample['displ']}, ",
        f"and its label: {train_labels.iloc[sample_idx]}",
        f" with a distance of {dist[0][i]:.4f}" )

## Task: Now, generate another new test sample (from Step 1.2) and redo the exercise.
> you must use at least one different test sample

> you must try different values for `k_value` variable and interpret the results accordingly

In [41]:
# your code
# ...
# ...
# ...

   year  cylinders  displ
0  1990          4    2.0

# Group exercise 2: try regression now on this vehicle.csv

Using the `vehicles.csv` dataset, let's try out sklearn with regression:
- load the data, get the right subset
- set predictors and target variables

In [45]:
# load in the vehicles.csv data for scikit learn
import pandas
import numpy

# load data, get the right subset
path            = '/content/drive/MyDrive/cs167_fall26/datasets/vehicles.csv'
data            = pandas.read_csv(path, low_memory=False)
# select only a subset of rows/samples whose fuelType is 'Regular'
# among those rows, select only a subset of predictors ['year', 'cylinders', 'displ', 'comb08']
gas_vehicles    = data[data['fuelType']=='Regular'][['year', 'cylinders', 'displ', 'comb08']]
gas_vehicles.dropna(inplace=True)

# set the predictor variables and target variable
predictors      = ['year', 'cylinders', 'displ']
target          = 'comb08'

# separate the data and labels
train_data      = gas_vehicles[predictors]
train_labels    = gas_vehicles[target]
print(f"total training samples after cleanup: {train_data.shape[0]}")

total training samples after cleanup: 26860

## Step 1.2: Generate a new test sample
Let's generate a new instance with:

In [ ]:
# your code
# ...
# ...
# ...

## Steps 2-4: do the next steps:

- build our model using [**neighbors.KNeighborsRegressor()**](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#sklearn.neighbors.KNeighborsRegressor)
- fit our model using `fit()` and passing in `train_data` and `train_labels`
- get our predictions for a new unknown sample by calling `predict()`

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
# your code

# create our model

# fit (train) the model to the data

# use the trained model to get predictions from our test_data

Label of the new sample according to 5-NN: 19.4

Check the individual nearest neighbors and their labels using
>[KNeighborsClassifier.kneighbors() method](https://scikit-learn.org/0.19/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier.kneighbors)

In [ ]:
# your code
# ...
# ...
# ...