<a href="https://colab.research.google.com/github/alimoorreza/CS167-fall26-notes/blob/main/Day09_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day09
## Cross-Validation

#### CS167: Machine Learning, Fall 2026


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_fall26/cs167_syllabus_fall26.pdf)

In [2]:
#run this cell if you're using Colab:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

# load data
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris_data = pd.read_csv(path)
iris_data.head()

   sepal length  sepal width  petal length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Cross-Validation

Don't train the model on the testing data!

<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day04_cross_validation.png" width=400/>
</div>

## Cross-Validation Code:

A good rule of thumb is that we like to train our model with 80% of the given data examples (training set), and test it on 20% of the given data examples (training set).

Splitting datasets into training and testing sets with a Pandas DataFrame:

## Let's see how accurate our kNN model is:

Start with loading the data and setting up some cross-validation:

## Split Data

Cross-Validation is an important step in machine learning which enables us to evaluate our models. To do this, we need to split our data into `train_data` and `test_data`.
<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day04_cross_validation.png" width=600/>
</div>

Sklearn takes this a step futher and splits the data up into 4 pieces:

<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day06_traintestsplit.png" width=600/>
</div>

- `train_data`: holds the predictor variables of the training set
- `train_sln`: holds the target variable of the training set
- `test_data`: holds the predictor variables of the testing set
- `test_sln`: holds the target varibles of the testing set

In [14]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split # **NEW MODULE** to import


predictors  = ['sepal length', 'sepal width','petal length', 'petal width']
target      = "species"
train_data, test_data, train_labels, test_labels = train_test_split(iris_data[predictors],
                                                                    iris_data[target],
                                                                    test_size = 0.2,
                                                                    random_state=41)

print('number of test samples:', test_data.shape[0])
print('number of train samples:', train_data.shape[0])

number of test samples: 30
number of train samples: 120

In [11]:
train_data.head()

     sepal length  sepal width  petal length  petal width
79            5.7          2.6           3.5          1.0
54            6.5          2.8           4.6          1.5
106           4.9          2.5           4.5          1.7
90            5.5          2.6           4.4          1.2
145           6.7          3.0           5.2          2.3

<!--Putting everything together

'''

import pandas as pd
import numpy as np
iris = pd.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv')

#shuffle the iris "sampling" the full set in random order
shuffled_data = iris.sample(frac=1, random_state=41)
#shuffled_data = iris.sample(frac=1, random_state=10)

# set up training and testing set
number_of_test_samples = 20
iris_test     = shuffled_data.iloc[0:number_of_test_samples] #test on the first 20 rows of shuffled
iris_train    = shuffled_data.iloc[number_of_test_samples:] #train on the rest

predictors    = ['sepal length', 'sepal width', 'petal length', 'petal width']
target        = 'species'

# separating 'predictors' and 'target' for test split
test_data     = iris_test[predictors]
test_labels   = iris_test[target]

# separating 'predictors' and 'target' for train split
train_data    = iris_train[predictors]
train_labels  = iris_train[target]

print('number of test samples:', test_data.shape[0])
print('number of train samples:', train_data.shape[0])
'''
-->