<a href="https://colab.research.google.com/github/alimoorreza/CS167-fall26-notes/blob/main/Day12_Scikit_Learn_More_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day12
## Scikit Learn Practice

#### CS167: Machine Learning, Fall 2026


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_fall26/cs167_syllabus_fall26.pdf)

# Overview of the Scikit Learn 'Algorithm':

When working in Scikit Learn (`sklearn`), there is a general pattern that we can follow to implement any supported machine learning algorithm.

It goes like this:
1. Load your data using `pd.read_csv()`
2. Split your data `train_test_split()`
3. Create your classifier/regressor object
4. Call `fit()` to train your model
5. Call `predict()` to get predictions
6. Call a metric function to measure the performance of your model.

## All together, it looks something like this:

In [2]:
# Mount your drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
#classic scikit-learn algorithm

#0. import libraries
import sklearn
import pandas
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import neighbors

#1. load data
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris_data = pandas.read_csv(path)

#2. split data
predictors = ['sepal length', 'sepal width','petal length', 'petal width']
target = "species"
train_data, test_data, train_sln, test_sln = \
        train_test_split(iris_data[predictors], iris_data[target], test_size = 0.15, random_state=3)



#for k in range(1, 50, 2):
#3. Create classifier/regressor object (change these parameters for Exercise #1)
# dt = tree.DecisionTreeClassifier()
#my_knn = neighbors.KNeighborsClassifier(n_neighbors=5, weights='distance') # weighted-kNN
#my_knn_weighted = neighbors.KNeighborsClassifier(n_neighbors=5, weights='distance') # weighted-kNN
my_tree = tree.DecisionTreeClassifier(max_depth=10)


#4. Call fit (to train the classification/regression model)
#dt.fit(train_data,train_sln)
#my_knn_weighted.fit( train_data, train_sln )
my_tree.fit( train_data, train_sln )


#5. Call predict to generate predictions
#predictions = my_knn_weighted.predict(test_data)
predictions = my_tree.predict(test_data)

#6. Call a metric function to measure performance
#print("Accuracy: (", k, 'NN): ', metrics.accuracy_score(test_sln, predictions))
print("Accuracy:", metrics.accuracy_score(test_sln, predictions))


# Show the acutal and predicted (this isn't necessary, but may help catch bugs)
'''print("--------------------------------------------------------------")
print(f"{'ACTUAL':<{20}} {'PREDICTIONS':<{20}}")
for i in range(len(test_sln)):
    actual_sample     = test_sln.iloc[i]
    predicted_sample  = predictions[i]
    print(f"{actual_sample:<{20}} {predicted_sample:<{20}}")

print("--------------------------------------------------------------")
'''


#print out a confusion matrix
iris_labels= ["Iris-setosa", "Iris-versicolor","Iris-virginica"]
conf_mat = metrics.confusion_matrix(test_sln, predictions, labels=iris_labels)
print(pandas.DataFrame(conf_mat,index = iris_labels, columns = iris_labels))

Accuracy: 0.9565217391304348
                 Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa                9                0               0
Iris-versicolor            0                5               1
Iris-virginica             0                0               8

In [ ]:
train_data.head()

     sepal length  sepal width  petal length  petal width
76            6.8          2.8           4.8          1.4
5             5.4          3.9           1.7          0.4
109           7.2          3.6           6.1          2.5
134           6.1          2.6           5.6          1.4
67            5.8          2.7           4.1          1.0

In [ ]:
train_sln.head()

76     Iris-versicolor
5          Iris-setosa
109     Iris-virginica
134     Iris-virginica
67     Iris-versicolor
Name: species, dtype: object

# Step 6: Evaluate the Model

Now that we have some predictions, we need to check to see how close we were by passing our predictions and the actual correct answers into a metric function.

| **Type of ML** | **Metric**                | **Description**                                                                                       | Scikit Learn                                                                                                                                                            |
|----------------|---------------------------|:-------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Classification | Accuracy                  | Number correct examples divided by total number                                                       | [`sklearn.metrics.accuracy_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)                                               |
| Classification | Confusion Matrix          | Detailed table of where our model got confused.                                                       | [`sklearn.metrics.confusion_matrix`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html#sklearn.metrics.confusion_matrix)          |
| Regression     | Mean Absolute Error (MAE) | The average absolute distance from the target variable                                                | [`sklearn.metrics.mean_absolute_error`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html#sklearn.metrics.mean_absolute_error) |
| Regression     | Mean Squared Error (MSE)  | The average squared distance from the target variable                                                 | [`sklearn.metrics.mean_squared_error`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html#sklearn.metrics.mean_squared_error)    |
| Regression     | $R^2$                     | 1: perfectly fit data 0: same performance as guessing the mean of the target variable -1: really bad. | [`sklearn.metrics.r2_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html#sklearn.metrics.r2_score)                                  |

Available metrics can be found in the sklearn documentation [[sklearn metrics]](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics)

In [ ]:
from sklearn import metrics
#6. call a metric function to evaluate the model
print("Accuracy:", metrics.accuracy_score(test_sln, predictions))

Accuracy: 0.9

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt
#print out a confusion matrix
iris_labels= ["Iris-setosa", "Iris-versicolor","Iris-virginica"]
conf_mat = metrics.confusion_matrix(test_sln, predictions, labels=iris_labels)
print(conf_mat)

[[ 9  0  0]
 [ 0 10  1]
 [ 0  2  8]]

# Normalizing using `StandardScaler`

**Documentation**: [`sklearn.preprocessing.StandardScaler`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [ ]:
train_data.head()

     sepal length  sepal width  petal length  petal width
76            6.8          2.8           4.8          1.4
5             5.4          3.9           1.7          0.4
109           7.2          3.6           6.1          2.5
134           6.1          2.6           5.6          1.4
67            5.8          2.7           4.1          1.0

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(train_data)

train_data_normalized = scaler.transform(train_data)
test_data_normalized = scaler.transform(test_data)
train_data_normalized

array([[ 1.18911441, -0.60698951,  0.58314134,  0.26658738],
       [-0.56982521,  1.93944997, -1.20210552, -1.06634951],
       [ 1.69166859,  1.24496647,  1.33179325,  1.73281796],
       [ 0.3096446 , -1.06997851,  1.04385021,  0.26658738],
       [-0.06727103, -0.83848401,  0.18002108, -0.26658738],
       [-1.19801793, -1.5329675 , -0.28068778, -0.26658738],
       [ 1.06347587,  0.08749398,  0.52555273,  0.39988107],
       [-0.06727103,  2.17094447, -1.49004856, -1.33293689],
       [-1.32365648,  0.78197748, -1.0869283 , -1.33293689],
       [ 1.31475296,  0.08749398,  0.92867299,  1.1996432 ],
       [ 0.93783733, -0.37549501,  0.46796412,  0.13329369],
       [-1.82621066, -0.37549501, -1.37487134, -1.33293689],
       [-0.8211023 ,  1.01347198, -1.31728273, -1.33293689],
       [ 1.06347587, -0.14400051,  0.69831856,  0.66646845],
       [-1.70057211, -1.764462  , -1.43245995, -1.1996432 ],
       [ 0.68656024, -0.83848401,  0.87108438,  0.93305583],
       [ 0.43528315, -1.9959565 ,  0.41037552,  0.39988107],
       [ 0.68656024, -0.60698951,  1.04385021,  1.1996432 ],
       [-0.06727103, -0.83848401,  0.06484387,  0.        ],
       [-1.57493357,  1.24496647, -1.60522577, -1.33293689],
       [-0.94674084,  1.01347198, -1.37487134, -1.1996432 ],
       [ 0.3096446 , -0.14400051,  0.64072995,  0.79976214],
       [ 0.68656024,  0.31898848,  0.41037552,  0.39988107],
       [-0.94674084,  0.55048298, -1.20210552, -0.93305583],
       [ 0.18400606, -0.83848401,  0.75590717,  0.53317476],
       [-0.06727103, -0.83848401,  0.75590717,  0.93305583],
       [-0.56982521, -0.14400051,  0.41037552,  0.39988107],
       [-1.32365648, -0.14400051, -1.37487134, -1.1996432 ],
       [-1.07237939,  0.31898848, -1.49004856, -1.33293689],
       [-0.06727103, -0.83848401,  0.75590717,  0.93305583],
       [ 1.4403915 ,  0.31898848,  0.52555273,  0.26658738],
       [ 0.3096446 , -0.60698951,  0.52555273,  0.        ],
       [-1.19801793,  0.08749398, -1.31728273, -1.46623058],
       [ 0.56092169,  0.78197748,  1.04385021,  1.59952427],
       [-0.94674084,  1.70795547, -1.31728273, -1.1996432 ],
       [ 0.81219878, -0.14400051,  0.9862616 ,  0.79976214],
       [-0.19290958, -0.37549501,  0.23760969,  0.13329369],
       [-1.07237939,  1.24496647, -1.37487134, -1.33293689],
       [-1.32365648, -0.14400051, -1.37487134, -1.46623058],
       [ 1.18911441,  0.31898848,  1.21661603,  1.46623058],
       [ 0.05836751,  0.31898848,  0.58314134,  0.79976214],
       [-0.56982521,  1.47646097, -1.31728273, -1.33293689],
       [-1.32365648,  0.78197748, -1.25969412, -1.33293689],
       [-0.94674084, -1.30147301, -0.45345361, -0.13329369],
       [ 0.68656024,  0.08749398,  0.9862616 ,  0.79976214],
       [ 0.56092169,  0.55048298,  1.27420464,  1.73281796],
       [-1.19801793,  0.08749398, -1.31728273, -1.46623058],
       [ 1.06347587,  0.55048298,  1.10143882,  1.1996432 ],
       [-0.19290958, -0.14400051,  0.23760969,  0.        ],
       [-1.44929502,  0.31898848, -1.25969412, -1.33293689],
       [-0.94674084,  0.78197748, -1.31728273, -1.33293689],
       [ 1.94294568, -0.60698951,  1.33179325,  0.93305583],
       [ 2.31986132,  1.70795547,  1.6773249 ,  1.33293689],
       [-0.06727103, -0.60698951,  0.75590717,  1.59952427],
       [-0.19290958, -0.60698951,  0.18002108,  0.13329369],
       [-0.8211023 , -0.83848401,  0.06484387,  0.26658738],
       [ 0.56092169, -1.764462  ,  0.35278691,  0.13329369],
       [-0.94674084,  1.70795547, -1.0869283 , -1.06634951],
       [-0.44418667,  1.01347198, -1.43245995, -1.33293689],
       [ 0.68656024,  0.31898848,  0.87108438,  1.46623058],
       [ 1.06347587,  0.55048298,  1.10143882,  1.73281796],
       [ 1.31475296,  0.08749398,  0.64072995,  0.39988107],
       [ 1.56603005, -0.14400051,  1.21661603,  1.1996432 ],
       [ 0.05836751, -0.14400051,  0.23760969,  0.39988107],
       [ 2.31986132, -0.60698951,  1.6773249 ,  1.06634951],
       [-1.32365648,  0.08749398, -1.25969412, -1.33293689],
       [ 0.56092169, -0.60698951,  0.75590717,  0.39988107],
       [-1.9518492 , -0.14400051, -1.54763717, -1.46623058],
       [-0.19290958, -0.60698951,  0.41037552,  0.13329369],
       [ 0.93783733, -0.14400051,  0.35278691,  0.26658738],
       [ 0.68656024, -0.60698951,  1.04385021,  1.33293689],
       [ 0.43528315,  0.78197748,  0.92867299,  1.46623058],
       [-0.8211023 ,  2.40243897, -1.31728273, -1.46623058],
       [-0.44418667, -1.5329675 ,  0.00725526, -0.13329369],
       [-0.56982521,  1.93944997, -1.43245995, -1.06634951],
       [ 0.3096446 , -0.14400051,  0.46796412,  0.26658738],
       [ 0.68656024, -0.37549501,  0.2951983 ,  0.13329369],
       [ 0.18400606,  0.78197748,  0.41037552,  0.53317476],
       [-1.19801793, -0.14400051, -1.37487134, -1.33293689],
       [ 1.69166859,  0.31898848,  1.27420464,  0.79976214],
       [-0.94674084,  1.70795547, -1.25969412, -1.33293689],
       [ 1.06347587, -1.30147301,  1.15902742,  0.79976214],
       [ 0.3096446 , -0.60698951,  0.12243247,  0.13329369],
       [ 1.06347587, -0.14400051,  0.81349577,  1.46623058],
       [ 0.56092169,  0.55048298,  0.52555273,  0.53317476],
       [-0.31854812, -0.60698951,  0.64072995,  1.06634951],
       [ 0.3096446 , -0.37549501,  0.52555273,  0.26658738],
       [-0.19290958,  1.70795547, -1.20210552, -1.1996432 ],
       [ 2.19422277, -0.14400051,  1.61973629,  1.1996432 ],
       [-0.31854812, -0.37549501, -0.10792196,  0.13329369],
       [ 0.81219878, -0.14400051,  0.81349577,  1.06634951],
       [ 0.81219878, -0.60698951,  0.46796412,  0.39988107],
       [-0.8211023 ,  0.78197748, -1.37487134, -1.33293689],
       [ 0.18400606, -0.37549501,  0.41037552,  0.39988107],
       [ 0.56092169, -1.30147301,  0.69831856,  0.93305583],
       [-1.07237939,  0.55048298, -1.37487134, -1.33293689],
       [-0.31854812, -0.83848401,  0.23760969,  0.13329369],
       [-0.56982521,  0.78197748, -1.20210552, -1.33293689],
       [-1.19801793,  0.08749398, -1.31728273, -1.46623058],
       [-0.69546375,  1.47646097, -1.31728273, -1.33293689],
       [-0.19290958, -1.06997851, -0.16551057, -0.26658738],
       [ 0.56092169, -0.83848401,  0.64072995,  0.79976214],
       [-0.44418667,  2.63393346, -1.37487134, -1.33293689],
       [-1.07237939,  1.01347198, -1.25969412, -0.79976214],
       [ 1.31475296,  0.31898848,  1.10143882,  1.46623058],
       [-1.07237939,  0.78197748, -1.31728273, -1.33293689],
       [ 0.18400606, -1.9959565 ,  0.12243247, -0.26658738],
       [ 0.05836751, -0.14400051,  0.75590717,  0.79976214],
       [ 0.43528315, -0.37549501,  0.2951983 ,  0.13329369],
       [ 0.81219878,  0.31898848,  0.75590717,  1.06634951],
       [ 0.81219878, -0.14400051,  1.15902742,  1.33293689],
       [-0.31854812, -1.30147301,  0.06484387, -0.13329369],
       [-0.44418667, -1.06997851,  0.35278691,  0.        ],
       [ 1.69166859, -0.14400051,  1.15902742,  0.53317476],
       [-1.07237939, -2.4589455 , -0.16551057, -0.26658738],
       [-1.44929502,  0.31898848, -1.43245995, -1.33293689],
       [-0.31854812, -0.14400051,  0.41037552,  0.39988107],
       [-0.44418667, -1.5329675 , -0.05033335, -0.26658738],
       [-1.07237939,  0.78197748, -1.25969412, -1.06634951],
       [-1.07237939, -1.764462  , -0.28068778, -0.26658738],
       [ 0.18400606, -1.9959565 ,  0.69831856,  0.39988107],
       [ 0.18400606, -0.14400051,  0.58314134,  0.79976214],
       [ 1.81730714, -0.37549501,  1.44697046,  0.79976214],
       [-0.94674084,  1.47646097, -1.31728273, -1.06634951],
       [-0.94674084,  1.01347198, -1.37487134, -1.33293689],
       [ 2.57113841,  1.70795547,  1.50455907,  1.06634951],
       [-1.19801793, -1.30147301,  0.41037552,  0.66646845]])

# Scikit Learn Practice:

# 💬 Group Exercise #1:

1. Build a knn (try using [`sklearn.neighbors.kNeighborsClassifier`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)) and use it on the Iris Dataset
    - is there a difference in performance between using a **weighted** or **unweighted** knn?
    - what if you change the number of nearest neighbors to 21?

In [9]:
#from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas

#1. load data
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris_data = pandas.read_csv(path)

#2. split data
predictors = ['sepal length', 'sepal width','petal length', 'petal width']
target = "species"
train_data, test_data, train_sln, test_sln = \
        train_test_split(iris_data[predictors], iris_data[target], test_size = 0.15, random_state=3)


# build your model
knn = neighbors.KNeighborsClassifier(n_neighbors=17)


# use fit() to train your model
knn.fit(train_data, train_sln)

# get predictions on the test_data
predictions = knn.predict(test_data)

# see how close your predictions were using an appropriate metric
'''print(f"predictions: {predictions}")
print(f"actual labels: {test_sln}")'''
acc = accuracy_score(test_sln, predictions)
print(f"accuracy: {acc}")
conf_mat = confusion_matrix(test_sln, predictions)
df = pandas.DataFrame(data=conf_mat, index=iris_labels, columns=iris_labels)
df.head()

accuracy: 1.0

                 Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa                9                0               0
Iris-versicolor            0                6               0
Iris-virginica             0                0               8

# Let's try regression now:

Using the `vehicles.csv` dataset, let's try out sklearn with regression:
- load the data, get the right subset
- set predictors and target variables
- use `train_test_split()` to split the data

In [11]:
# load in the vehicles.csv data for scikit learn
import pandas
import numpy
from sklearn.model_selection import train_test_split

# load data, get the right subset
path = '/content/drive/MyDrive/cs167_fall26/datasets/vehicles.csv'
data = pandas.read_csv(path)
gas_vehicles = data[data['fuelType']=='Regular'][['year', 'cylinders', 'displ', 'comb08']]
gas_vehicles.dropna(inplace=True)

# set the predictor variables and target variable
predictors= ['year', 'cylinders', 'displ']
target= 'comb08'

# use train_test_split() to split the data
train_data, test_data, train_sln, test_sln = train_test_split(gas_vehicles[predictors], gas_vehicles[target], test_size = 0.2, random_state=41)
train_data.head()

/tmp/ipykernel_4301/799766042.py:8: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pandas.read_csv(path)

       year  cylinders  displ
4256   1985        4.0    2.2
2685   1995        6.0    4.0
35058  2020        6.0    4.3
10678  1986        6.0    2.8
18702  1984        8.0    5.0

In [ ]:
train_sln.head()

4256     24
2685     16
35058    15
10678    19
18702    16
Name: comb08, dtype: int64

And then we do the next steps:
- build our model using `neighbors.KNeighborsRegressor()`
- fit our model using `fit()` and passing in `train_data` and `train_sln`
- get our predictions by calling `predict()`
- evaluate our predictions using `metrics.mean_squared_error()`, and `metrics.r2_score()`

In [12]:
from sklearn import tree
from sklearn import neighbors
from sklearn import metrics

# create our model
#my_tree = tree.DecisionTreeRegressor()
weighted_knn = neighbors.KNeighborsRegressor(n_neighbors=19, weights='distance')


# fit (train) the model to the data
#my_tree.fit( train_data, train_sln)
weighted_knn.fit( train_data, train_sln)

# use the trained model to get predictions from our test_data
#predictions = my_tree.predict( test_data )
predictions = weighted_knn.predict( test_data )

# use a metric to see how good our predictions are
print("R2: ", metrics.r2_score(test_sln, predictions))
print("MAE: ", metrics.mean_absolute_error(test_sln, predictions))
print("MSE: ", metrics.mean_squared_error(test_sln, predictions))

R2:  0.8029335877274243
MAE:  1.6385118835780408
MSE:  5.924918593283533

# 💬 Group Exercise #2: 🚗 🛺 🏎
Look up an appropriate Decision Tree algorithm and apply it to the vehicles data:
- https://scikit-learn.org/stable/modules/classes.html
- Using Default values of the decision tree, what is the $R^2$ metric?
  - [Check sklearn $R^2$ metric](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html)
- Interpret the $R^2$ value... is it good or bad?

In [ ]:
# Reference: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor
# HINT: you could override the default parameter of tree.DecisionTreeRegressor() such as criterion='squared_error' or criterion='absolute_error'

# your code
# ...
# ...
# ...

# 💬 Group Exercise #3:
Change your decision tree to have a `max_depth` of 3.
- does this help or hurt the decision tree performance?

Compare your decision tree to a kNN algorithm:
- what values of k seem to help the performance?
- What else can you do to help the performance?

Can you get a higher $R^2$ value using a knn algorithm or a decision tree?
- what does this indicate about the data?

In [ ]:
# Reference: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor
# HINT: you could override the default parameter of tree.DecisionTreeRegressor() such as criterion='squared_error' or criterion='absolute_error'
#       and 'max_depth' with appropriate value

# your code
# ...
# ...
# ...

# 💬 Group Exercise #4: 🐧🧊

Try out the `penguins_size.csv` dataset.
- Scikit learn Deicsion Trees and kNN only work with numeric data.
    - What will you need to do to get the penguin dataset to work? Hint: [`pandas.get_dummies()`](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html) and [`pandas.DataFrame.replace()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html) will help.
- What is the best accuracy you can get if you use `species` as the target variable?
- Which model does the best?
- What parameters work the best?
- Does normalizing the data make a difference? If so, how?

In [13]:
import pandas as pd
penguins = pd.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/penguins_size.csv')
print('shape of penguins: ', penguins.shape)
penguins.head()

shape of penguins:  (344, 7)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [14]:
# since target='species' can have only 3 discrete values ie, hence you should formulate a CLASSIFICATION problem for this part
penguin_labels = penguins['species'].unique()
print(f"unique target column values {penguin_labels}")

unique target column values ['Adelie' 'Chinstrap' 'Gentoo']

### Things to Notice: `pd.get_dummies()`
- ``island`, `sex` used to be categorical variables, but they no longer exist in `penguin_dummies`
- instead, we have `island_something`, or `sex_something`, etc.
- when we call `pd.get_dummies()`, we pass in the original dataframe, and the columns we want to convert
- `pd.get_dummies()` returns a new dataframe without the categorical columns.

In [15]:
# do pre-processing here: replace() and get_dummies() will help.
print(f"number of columns in penguins_dataset before replacing categorical values with pd.get_dummies(): {penguins.shape[1]}")
penguins_dummies = pd.get_dummies(penguins, columns=['island', 'sex'])
print(f"number of columns in penguins_dataset after replacing categorical values with pd.get_dummies(): {penguins_dummies.shape[1]}")
penguins_dummies.head()

# do pre-processing here: clean up your data now so that there is no NaN value
print(f"size of penguins_dataset before dropping NaN entries: {penguins_dummies.shape}")
penguins_dummies.dropna(inplace=True)
print(f"size of penguins_dataset after dropping NaN entries: {penguins_dummies.shape}")

number of columns in penguins_dataset before replacing categorical values with pd.get_dummies(): 7
number of columns in penguins_dataset after replacing categorical values with pd.get_dummies(): 11
size of penguins_dataset before dropping NaN entries: (344, 11)
size of penguins_dataset after dropping NaN entries: (342, 11)

In [ ]:
# train_test_split
target= 'species'
predictors = penguins_dummies.columns.drop(target)
train_data, test_data, train_sln, test_sln = train_test_split(penguins_dummies[predictors], penguins_dummies[target], test_size = 0.2, random_state=41)
train_data.head()

,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,island_Biscoe,island_Dream,island_Torgersen,sex_.,sex_FEMALE,sex_MALE
284,45.8,14.2,219.0,4700.0,True,False,False,False,True,False
275,45.0,15.4,220.0,5050.0,True,False,False,False,False,True
37,42.2,18.5,180.0,3550.0,False,True,False,False,True,False
119,41.1,18.6,189.0,3325.0,False,False,True,False,False,True
109,43.2,19.0,197.0,4775.0,True,False,False,False,False,True

In [ ]:
#build and test your models here
# try do train/test a vanilla kNN with k=21

# your code
# ...
# ...
# ...

# 💬 Group Exercise #5: 🐧🧊

Now, switch the target variable from `species` to `body_mass_g`. This turns the problem into a regression.
- Find the model that works the best for this problem as a regression. Models could be:
    - i) knn-regressor,
    - ii) weighted knn regressor, and
    - iii) decision tree regressor
- What metric makes the most sense to use?
- What parameters give you the best performance?
- Does normalizing the data make a difference in the performance?

In [16]:
penguins = pd.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/penguins_size.csv')

In [ ]:
# pre-processing (replace() and get_dummies())

In [17]:
target      = 'body_mass_g'
predictors  = penguins.columns.drop(target)
train_data, test_data, train_sln, test_sln = train_test_split(penguins[predictors], penguins[target], test_size = 0.2, random_state=41)
train_data.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,sex
214,Chinstrap,Dream,45.7,17.0,195.0,FEMALE
275,Gentoo,Biscoe,45.0,15.4,220.0,MALE
36,Adelie,Dream,38.8,20.0,190.0,MALE
202,Chinstrap,Dream,48.1,16.4,199.0,FEMALE
108,Adelie,Biscoe,38.1,17.0,181.0,FEMALE

In [ ]:
# build and test your models here:
# Model: kNN


# your code
# ...
# ...
# ...

In [ ]:
# build and test your models here:
# Model: weighted kNN with k=21



# your code
# ...
# ...
# ...

In [ ]:
# build and test your models here:
# Model: DecisionTreeRegressor()



# your code
# ...
# ...
# ...